services:
  - type: web
    name: inkstation-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PORT
        value: "25855"
      - key: DB_NAME
        value: inkstation
      - key: DB_SSL
        value: "true"
      - key: FRONTEND_URL
        value: https://aluguel-macas.vercel.app
